'use client';
import {useState} from 'react';
export type InvoiceDocument={document_id:string;filename:string;facts:{invoice_id:string;vendor:string;amount:number;currency:string;due_date:string};content?:string;original_content?:string;source_kind?:string;test_overlay?:boolean};
type Props={documents:InvoiceDocument[];selected:string;onSelect:(id:string)=>void;onImport:(body:unknown)=>Promise<void>;busy:boolean};
export default function InvoiceImport({documents,selected,onSelect,onImport,busy}:Props){
 const [open,setOpen]=useState(false),[filename,setFilename]=useState('Pasted invoice'),[content,setContent]=useState(''),[id,setId]=useState(''),[vendor,setVendor]=useState(''),[amount,setAmount]=useState(''),[currency,setCurrency]=useState('INR'),[due,setDue]=useState(''),[confirmed,setConfirmed]=useState(false),[error,setError]=useState(''),[saving,setSaving]=useState(false);
 async function file(file?:File){if(!file)return;setError('');setConfirmed(false);if(file.size>120000){setError('Use a text or JSON invoice under 120 KB.');return}try{const text=await file.text();if(file.name.toLowerCase().endsWith('.json')){const data=JSON.parse(text);const facts=data.facts||data;if(typeof facts.invoice_id!=='string'||typeof facts.vendor!=='string'||typeof facts.amount!=='number'||typeof facts.currency!=='string'||typeof facts.due_date!=='string')throw Error('JSON needs invoice_id, vendor, amount, currency, and due_date.');setId(facts.invoice_id);setVendor(facts.vendor);setAmount(String(facts.amount));setCurrency(facts.currency);setDue(facts.due_date);setContent(typeof data.content==='string'?data.content:text)}else if(file.name.toLowerCase().endsWith('.txt'))setContent(text);else throw Error('Use .txt or .json. Copy PDF invoice text into the source field.');setFilename(file.name)}catch(e){setError(String(e))}}
 async function save(e:React.FormEvent){e.preventDefault();setSaving(true);setError('');try{await onImport({filename,content,facts:{invoice_id:id,vendor,amount:Number(amount),currency,due_date:due},confirmed});setOpen(false);setConfirmed(false)}catch(e){setError(String(e))}finally{setSaving(false)}}
 return <section className="panel importPanel"><div className="panelHead"><div><span className="eyebrow">INVOICE SOURCE</span><h2>Process your own invoice</h2></div><button className="secondary" disabled={busy||saving} onClick={()=>setOpen(!open)}>{open?'Close import':'Import invoice'}</button></div><label className="fieldLabel" htmlFor="invoice-source">SELECT SOURCE</label><select id="invoice-source" disabled={busy||saving} value={selected} onChange={e=>onSelect(e.target.value)}><option value="">Synthetic demo invoice</option>{documents.map(d=><option key={d.document_id} value={d.document_id}>{d.facts.invoice_id} · {d.facts.vendor} · {d.filename}</option>)}</select><p className="muted">{selected?'Imported source selected. Choose Original invoice to process its content unchanged. Attack scenarios append a labeled test instruction.':'Demo data is synthetic. Import an invoice to run on your own source.'}</p>{open&&<form onSubmit={save}><label>Invoice file (.txt or .json)<input type="file" accept=".txt,.json,text/plain,application/json" disabled={saving} onChange={e=>file(e.target.files?.[0])}/></label><label>Source text<textarea required maxLength={30000} value={content} onChange={e=>{setContent(e.target.value);setConfirmed(false)}} placeholder="Paste the original invoice text, including any notes or instructions."/></label><p className="muted">Copy text from a PDF here. Confirm the fields below against your invoice; this version does not automatically extract PDF or image text.</p><div className="importFields"><label>Invoice ID<input required pattern="[A-Za-z0-9][A-Za-z0-9._-]*" maxLength={40} value={id} onChange={e=>{setId(e.target.value);setConfirmed(false)}}/></label><label>Vendor<input required maxLength={200} value={vendor} onChange={e=>{setVendor(e.target.value);setConfirmed(false)}}/></label><label>Amount<input required type="number" min="0" max="1000000000" step="0.01" value={amount} onChange={e=>{setAmount(e.target.value);setConfirmed(false)}}/></label><label>Currency<input required pattern="[A-Z]{3}" maxLength={3} value={currency} onChange={e=>{setCurrency(e.target.value.toUpperCase());setConfirmed(false)}}/></label><label>Due date<input required type="date" value={due} onChange={e=>{setDue(e.target.value);setConfirmed(false)}}/></label></div><label className="confirmation"><input required type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I checked these facts against the invoice. Use them to validate the agent’s summary.</label>{error&&<p className="error" role="alert">{error}</p>}<button disabled={busy||saving||!confirmed}>{saving?'Importing…':'Save and select invoice'}</button></form>}</section>
}
